Meeting notes for Q1 and Q2 2024
InsightSoftwareConsortium/insightsoftwareconsortium.org pull request #101
Opened 2024-09-18 20:25 UTC by jjomier

Added meeting notes from ISC Council on 03/18/2024 and 06/17/2024

2024-09-18 20:57 UTC, dzenanz approved these changes

2024-09-19 17:19 UTC, thewtex requested changes
Outstanding, thank you @jjomier !

One minor request, can the title please be updated from:

> ISC Board Meeting - <Date>

to

> ISC Council Meeting - <Date>

?

This is a small but important distinction to account for our joining NumFOCUS as a Sponsored Project where the Board for our organization is technically the NumFOCUS Board.

2024-09-19 17:47 UTC, jjomier commented
Thanks for the clarification @thewtex - this is fixed now.

2024-09-19 23:04 UTC, thewtex approved these changes
@jjomier merci!

2024-09-19 23:04 UTC, merged